#!/bin/bash
# The following extensions are required for Juyter Lab
conda install -c conda-forge nodejs 
jupyter labextension install jupyterlab_3dmol
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter lab build
