#!/bin/bash
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=acc-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_linux-x64_bin.tar.gz"
tar -xzvf jdk-9.0.1_linux-x64_bin.tar.gz

export JAVA_HOME=/tmp/jdk-9.0.1/
export PATH=$JAVA_HOME/bin:$PATH


SPARK_VERSION='2.2.1'
HADOOP_VERSION='2.7'


curl http://mirror.cogentco.com/pub/apache/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark.tgz

cd /tmp && tar -xvzf /tmp/spark.tgz

SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
export PATH=$SPARK_HOME/bin:$PATH
export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH

export PYSPARK_SUBMIT_ARGS="--master local[*] pyspark-shell"
