#!/bin/bash
# set environment variables to sample files
# binder fails to launch when these environment variables are set???
#export MMTF_REDUCED=./resources/mmtf_reduced_sample/
#export MMTF_FULL=./resources/mmtf_full_sample/
#exec "$@"
