#!/bin/bash
# The following extensions are required for Juyter Lab
#conda install -c conda-forge nodejs 
jupyter labextension install jupyterlab_3dmol --no-build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter lab build
